// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9B4RbtXkAZ6VI26G3zZN20U_XuHXHQXU',
    appId: '1:208891187003:web:b627df594d664ee3abf11e',
    messagingSenderId: '208891187003',
    projectId: 'glovo-clone',
    authDomain: 'glovo-clone.firebaseapp.com',
    storageBucket: 'glovo-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9ROwdX3nMgJnRYFh43kEsijijDDfdbDg',
    appId: '1:208891187003:android:108bad2e09fe83c5abf11e',
    messagingSenderId: '208891187003',
    projectId: 'glovo-clone',
    storageBucket: 'glovo-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_cJW3QEUWepEqng6AKYCUoupC5ig-dwA',
    appId: '1:208891187003:ios:8b402d719c5cbecaabf11e',
    messagingSenderId: '208891187003',
    projectId: 'glovo-clone',
    storageBucket: 'glovo-clone.appspot.com',
    androidClientId: '208891187003-1h3r1hgoeqhp2s8kdvfee3k8dkh9t6vn.apps.googleusercontent.com',
    iosClientId: '208891187003-3crigc632mjakf9s0dt1bcjvqm0v3vvn.apps.googleusercontent.com',
    iosBundleId: 'com.example.glovo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_cJW3QEUWepEqng6AKYCUoupC5ig-dwA',
    appId: '1:208891187003:ios:8b402d719c5cbecaabf11e',
    messagingSenderId: '208891187003',
    projectId: 'glovo-clone',
    storageBucket: 'glovo-clone.appspot.com',
    androidClientId: '208891187003-1h3r1hgoeqhp2s8kdvfee3k8dkh9t6vn.apps.googleusercontent.com',
    iosClientId: '208891187003-3crigc632mjakf9s0dt1bcjvqm0v3vvn.apps.googleusercontent.com',
    iosBundleId: 'com.example.glovo',
  );
}
